defaultsteps:
  - CT2scsv_ct2_en
  - CT2scsv_ct2_de
  # - CT2scsv_jct_en
  # - CT2scsv_jct_de
  - categories_ct2_en
  - categories_ct2_de
  # - categories_jct_en
  # - categories_jct_de
  # - merge_en
  # - merge_de
  # - tofinalform_en
  # - tofinalform_de
  # - tohtml_en
  # - tohtml_de

step.CT2scsv_ct2_en:
  id_reference: ${workspace}/data/en/scsv_generated/ct2.csv
  input       : ${workspace}/data/en/scsv_generated/ct2.csv
  output      : ${workspace}/scsv_ct2_nocat_en.csv

step.CT2scsv_ct2_de:
  id_reference: ${workspace}/data/en/scsv_generated/ct2.csv
  input       : ${workspace}/data/de/scsv_generated/ct2.csv
  output      : ${workspace}/scsv_ct2_nocat_de.csv

step.CT2scsv_jct_en:
  id_reference: ${workspace}/data/en/scsv_generated/jct.csv
  input       : ${workspace}/data/en/scsv_generated/jct.csv
  output      : ${workspace}/scsv_jct_nocat_en.csv

step.CT2scsv_jct_de:
  id_reference: ${workspace}/data/en/scsv_generated/jct.csv
  input       : ${workspace}/data/de/scsv_generated/jct.csv
  output      : ${workspace}/scsv_jct_nocat_de.csv


step.categories_ct2_en:
  input  : ${workspace}/scsv_ct2_nocat_en.csv
  catfiles: 
    - ${workspace}/categories_ct2_en.csv
    - ${workspace}/categories_interaction_required.csv
  feedbackfile: ${workspace.template}/categories_interaction_required.csv
  output : ${workspace}/scsv_ct2_en.csv

step.categories_ct2_de:
  input  : ${workspace}/scsv_ct2_nocat_de.csv
  catfiles: 
    - ${workspace}/categories_ct2_de.csv
    - ${workspace}/categories_interaction_required.csv
  feedbackfile: ${workspace.template}/categories_interaction_required.csv
  output : ${workspace}/scsv_ct2_de.csv

step.categories_jct_en:
  input  : ${workspace}/scsv_jct_nocat_en.csv
  catfiles: 
    - ${workspace}/categories_jct_en.csv
    - ${workspace}/categories_interaction_required.csv
  feedbackfile: ${workspace.template}/categories_interaction_required.csv
  output : ${workspace}/scsv_jct_en.csv

step.categories_jct_de:
  input: ${workspace}/scsv_jct_nocat_de.csv
  catfiles: 
    - ${workspace}/categories_jct_de.csv
    - ${workspace}/categories_interaction_required.csv
  feedbackfile: ${workspace.template}/categories_interaction_required.csv
  output: ${workspace}/scsv_jct_de.csv

step.merge_en:
  input: 
    - ${workspace}/data/en/scsv_webdump/ct1.csv
    - ${workspace}/data/en/scsv_webdump/cto.csv
    - ${workspace}/scsv_ct2_en.csv
    # - ${workspace}/scsv_jct_en.csv
  output: ${workspace}/all_merged_en.csv

step.merge_de:
  input: 
    - ${workspace}/data/de/scsv_webdump/ct1.csv
    - ${workspace}/data/de/scsv_webdump/cto.csv
    - ${workspace}/scsv_ct2_de.csv
    - ${workspace}/scsv_jct_de.csv
  output: ${workspace}/all_merged_de.csv

step.tofinalform_en:
  input: ${workspace}/all_merged_en.csv
  output: ${workspace}/all_final_en.csv

step.tofinalform_de:
  input: ${workspace}/all_merged_de.csv
  output: ${workspace}/all_final_de.csv

step.tohtml_en:
  template_html: ${workspace}/data/en/html_template
  input: ${workspace}/all_final_en.csv
  output: ${workspace}/html_en/index.html

step.tohtml_de:
  template_html: ${workspace}/data/de/html_template
  input: ${workspace}/all_final_de.csv
  output: ${workspace}/html_de/index.html
