var plgGdprAllCookiesDisabledByScript=!1,detectedOldIPhone=!1;if(null!==navigator.userAgent.match(/iPhone/i)){var iphone4=480==window.screen.height,iphone5=568==window.screen.height;if(iphone4||iphone5)detectedOldIPhone=!0}
var plgGdprDisableAllCookies=function(b){var g=document.cookie.split("; "),a=["cookieconsent_status"];"undefined"!==typeof gdprJSessCook&&a.push(gdprJSessCook);"undefined"!==typeof gdprJAdminSessCook&&a.push(gdprJAdminSessCook);if(gdprConfigurationOptions.allowedCookies){var c=gdprConfigurationOptions.allowedCookies.split(",");a=a.concat(c)}c=function(b){for(var a=window.location.hostname.split(".");0<a.length;){var e=encodeURIComponent(b.split(";")[0].split("=")[0])+"=; expires=Thu, 01-Jan-1970 00:00:01 GMT; domain="+
a.join(".")+" ;path=",c=location.pathname.split("/");for(document.cookie=e+"/";0<c.length;){var d=c.join("/");d||(d="/");document.cookie=e+d;c.pop()}a.shift()}};for(var e=0;e<g.length;e++){for(var f=!0,h=0;h<a.length;h++)-1!=g[e].indexOf(a[h])&&(f=!1);f&&c(g[e])}b||!gdprConfigurationOptions.blockCookieDefine||detectedOldIPhone||Object.defineProperty(document,"cookie",{get:function(){return""},set:function(){return!0}});gdprConfigurationOptions.placeholderBlockedResources?jQuery("*[src*=gdprlock],*[data-source=gdprlock]").replaceWith('<div class="gdprlock-placeholder"><div class="gdprlock-placeholder-text">'+
gdprConfigurationOptions.placeholderBlockedResourcesText+"</div></div>"):jQuery("*[src*=gdprlock],*[data-source=gdprlock]").remove();plgGdprAllCookiesDisabledByScript=!0};
(function(){if("undefined"!==typeof gdpr_unset_categories_cookies)for(var b=0;b<gdpr_unset_categories_cookies.length;b++)for(var g=gdpr_unset_categories_cookies[b],a=window.location.hostname.split(".");0<a.length;){var c=encodeURIComponent(g.split(";")[0].split("=")[0])+"=; expires=Thu, 01-Jan-1970 00:00:01 GMT; domain="+a.join(".")+" ;path=",e=location.pathname.split("/");for(document.cookie=c+"/";0<e.length;){var f=e.join("/");f||(f="/");document.cookie=c+f;e.pop()}a.shift()}})();
gdprConfigurationOptions.lawByCountry||("opt-in"!=gdprConfigurationOptions.complianceType||localStorage.getItem("hasConsented")||localStorage.getItem("setConsentedCookie")||plgGdprDisableAllCookies(),"opt-out"==gdprConfigurationOptions.complianceType&&localStorage.getItem("hasDeclined")&&plgGdprDisableAllCookies());
jQuery(function(b){plgGdprAllCookiesDisabledByScript||(gdprConfigurationOptions.placeholderBlockedResources?jQuery("*[src*=gdprlock],*[data-source=gdprlock]").replaceWith('<div class="gdprlock-placeholder"><div class="gdprlock-placeholder-text">'+gdprConfigurationOptions.placeholderBlockedResourcesText+"</div></div>"):jQuery("*[src*=gdprlock],*[data-source=gdprlock]").remove());window.gdprIsCookieConsentPresent=function(b){b=("; "+document.cookie).split("; "+b+"=");return 2!=b.length?void 0:b.pop().split(";").shift()}("cookieconsent_status");
var g=function(){var a=b("iframe").length,c=!!navigator.mozGetUserMedia;gdprConfigurationOptions.blockExternalCookiesDomains&&a&&c&&localStorage.setItem("refreshIframeCache",!0);if(gdpr_enable_log_cookie_consent){if("opt-in"==gdprConfigurationOptions.complianceType)var e=localStorage.getItem("hasConsented");else"opt-out"==gdprConfigurationOptions.complianceType&&(e=!localStorage.getItem("hasDeclined"));b.ajax({type:"POST",url:gdpr_ajax_livesite+"index.php?option=com_gdpr&task=user.processGenericCookieCategories",
data:{gdpr_generic_cookie_consent:e?1:0}}).then(function(){window.location.reload()})}else setTimeout(function(){window.location.reload()},0)};b(document).on("click","a.cc-allow",function(a){"opt-out"==gdprConfigurationOptions.complianceType&&localStorage.getItem("hasDeclined")&&(localStorage.removeItem("hasDeclined"),localStorage.removeItem("hasDenyMessage"),localStorage.removeItem("hasExplititDeclinedAll"),localStorage.setItem("setAllowRevokedCookie",!0),g());"opt-out"!=gdprConfigurationOptions.complianceType||
localStorage.getItem("hasFirstDeclined")||b.ajax({type:"POST",url:gdpr_ajax_livesite+"index.php?option=com_gdpr&task=user.processGenericCookieCategories",data:{gdpr_generic_cookie_consent:1}})});localStorage.getItem("refreshIframeCache")&&(b("iframe").each(function(a,c){a=b(c).clone();b(c).after(a).remove()}),localStorage.getItem("setConsentedCookie")||localStorage.removeItem("refreshIframeCache"));window.cookieconsent.initialise({type:gdprConfigurationOptions.complianceType,layout:gdprConfigurationOptions.toolbarLayout,
theme:gdprConfigurationOptions.toolbarTheme,position:gdprConfigurationOptions.toolbarPosition,revokeposition:gdprConfigurationOptions.revokePosition,container:document.querySelector(gdprConfigurationOptions.containerSelector),palette:{popup:{background:gdprConfigurationOptions.popupBackground,text:gdprConfigurationOptions.popupText,link:gdprConfigurationOptions.popupLink},button:{background:gdprConfigurationOptions.buttonBackground,border:gdprConfigurationOptions.buttonBorder,text:gdprConfigurationOptions.buttonText},
highlight:{background:gdprConfigurationOptions.highlightBackground,border:gdprConfigurationOptions.highlightBorder,text:gdprConfigurationOptions.highlightText},highlightDismiss:{background:gdprConfigurationOptions.highlightDismissBackground,border:gdprConfigurationOptions.highlightDismissBorder,text:gdprConfigurationOptions.highlightDismissText},highlightOpacity:{opacity:gdprConfigurationOptions.highlightOpacity}},revokable:!!gdprConfigurationOptions.revokable,location:!!gdprConfigurationOptions.lawByCountry,
law:{regionalLaw:!gdprConfigurationOptions.lawByCountry},showLink:!!gdprConfigurationOptions.showLinks,static:!gdprConfigurationOptions.toolbarPositionmentType,dismissOnScroll:gdprConfigurationOptions.dismissOnScroll,dismissOnTimeout:gdprConfigurationOptions.dismissOnTimeout,animateRevokable:!!gdprConfigurationOptions.hideRevokableButton,onInitialise:function(b){"opt-out"==gdprConfigurationOptions.complianceType&&localStorage.getItem("setAllowRevokedCookie")&&(this.setStatus("allow",!0),localStorage.removeItem("setAllowRevokedCookie"))},
content:{header:gdprConfigurationOptions.headerText,message:gdprConfigurationOptions.messageText,dismiss:gdprConfigurationOptions.dismissText,allow:gdprConfigurationOptions.allowText,deny:gdprConfigurationOptions.denyText,link:gdprConfigurationOptions.cookiePolicyLinkText,href:gdprConfigurationOptions.cookiePolicyLink,privacylink:gdprConfigurationOptions.privacyPolicyLinkText,privacyhref:gdprConfigurationOptions.privacyPolicyLink},onStatusChange:function(a,c){c=this.options.type;var e=this.hasConsented();
if("opt-in"==c&&(e||b("a.cc-btn",this.element).hasClass("cc-allow"))&&"allow"==a){var f=localStorage.getItem("hasConsented"),h=localStorage.getItem("hasExplititDeclinedAll"),d={hasConsented:!0,timestamp:(new Date).getTime()};localStorage.setItem("hasConsented",JSON.stringify(d));plgGdprAllCookiesDisabledByScript&&localStorage.setItem("setConsentedCookie",!0);localStorage.removeItem("hasExplititDeclinedAll");gdprConfigurationOptions.preserveLockedCategories?b("input.cc-cookie-checkbox:not([readonly])").attr("disabled",
!1):b("input.cc-cookie-checkbox").attr("disabled",!1);if(gdprConfigurationOptions.disableFirstReload){d=!1;var l=parseInt(localStorage.getItem("autoActivateOnNextPage")),k=!localStorage.getItem("hasFirstAccepted");if(!k||1==l||h)f&&gdprIsCookieConsentPresent||(d=!0,g());gdpr_enable_log_cookie_consent&&k&&!d&&b.ajax({type:"POST",url:gdpr_ajax_livesite+"index.php?option=com_gdpr&task=user.processGenericCookieCategories",data:{gdpr_generic_cookie_consent:1}});k&&(d={hasFirstAccepted:!0,timestamp:(new Date).getTime()},
localStorage.setItem("hasFirstAccepted",JSON.stringify(d)))}else f&&gdprIsCookieConsentPresent||g()}"opt-in"!=c||e&&!b("a.cc-btn",this.element).hasClass("cc-deny")||"deny"!=a||(f=localStorage.getItem("hasConsented"),localStorage.removeItem("hasConsented"),localStorage.removeItem("setConsentedCookie"),d={hasDeclined:!0,timestamp:(new Date).getTime()},localStorage.setItem("hasFirstDeclined",JSON.stringify(d)),localStorage.setItem("hasExplititDeclinedAll",JSON.stringify(d)),this.setStatus("deny",!0),
gdprConfigurationOptions.preserveLockedCategories?b("input.cc-cookie-checkbox:not([readonly])").attr("disabled",!0):b("input.cc-cookie-checkbox").attr("disabled",!0),f?g():b.ajax({type:"POST",url:gdpr_ajax_livesite+"index.php?option=com_gdpr&task=user.processGenericCookieCategories",data:{gdpr_generic_cookie_consent:0}}).then(function(){gdprConfigurationOptions.reloadOnfirstDeclineall&&"undefined"!==typeof gdprUseCookieCategories&&window.location.reload()}));"opt-out"!=c||e||localStorage.getItem("hasDeclined")||
(plgGdprDisableAllCookies(!0),d={hasDeclined:!0,timestamp:(new Date).getTime()},localStorage.setItem("hasDeclined",JSON.stringify(d)),localStorage.setItem("hasFirstDeclined",JSON.stringify(d)),localStorage.setItem("hasExplititDeclinedAll",JSON.stringify(d)),gdprConfigurationOptions.preserveLockedCategories?b("input.cc-cookie-checkbox:not([readonly])").attr("disabled",!0):b("input.cc-cookie-checkbox").attr("disabled",!0),g());gdprConfigurationOptions.denyMessageEnabled&&"allow"==a&&localStorage.removeItem("hasDenyMessage")},
onPopupOpen:function(a){"opt-in"!=gdprConfigurationOptions.complianceType&&"opt-out"!=gdprConfigurationOptions.complianceType||!gdprConfigurationOptions.autoAcceptOnNextPage||a||localStorage.getItem("hasExplititDeclinedAll")||(a=localStorage.getItem("autoActivateOnNextPage"),2==parseInt(a)?(localStorage.setItem("autoActivateOnNextPage",1),"opt-in"==gdprConfigurationOptions.complianceType?(b("div.cc-window.cc-banner,div.cc-window.cc-floating").hide(),b("a.cc-btn.cc-allow").trigger("click")):"opt-out"==
gdprConfigurationOptions.complianceType&&setTimeout(function(){b("a.cc-btn.cc-allow").trigger("click")},100)):a||localStorage.setItem("autoActivateOnNextPage",2))}});if(gdprConfigurationOptions.trackExistingCheckboxSelectors)b(gdprConfigurationOptions.trackExistingCheckboxSelectors).on("change",function(a){parentForm=b(a.target).parents("form");var c={url:b(location).attr("href"),formid:parentForm.attr("id"),formname:parentForm.attr("name"),formfields:{}};b(this).is(":checked")&&0!=parseInt(b(this).val())?
(a=gdprConfigurationOptions.trackExistingCheckboxConsentLogsFormfields.split(","),a=a.map(function(b,a){return b.trim()}),b.each(a,function(a,f){a=b("input[name*="+f+"]:not(:hidden), input[id*="+f+"]:not(:hidden), textarea[name*="+f+"], textarea[id*="+f+"]",parentForm);a.length&&b.each(a,function(a,d){(a=b(d).attr("id"))||(a=b(d).attr("name"));a=a.replace(/[-_]/gi," ");a=a.replace(/[\[\]]/gi,"");a=a.replace("jform","");a=a.trim();d=b(d).val();c.formfields[a]=d})}),b.ajax({type:"POST",url:gdpr_ajax_livesite+
"index.php?option=com_gdpr&task=user.storeConsent&format=raw",data:c})):b.ajax({type:"POST",url:gdpr_ajax_livesite+"index.php?option=com_gdpr&task=user.deleteConsent&format=raw",data:c})})});
